Update map.dart 핀치 줌 오류 해결
kit-kitHub/Facilities_Info-Frontend pull request #25
Opened 2024-11-21 17:28 UTC by KangJiHyeock

핀치 줌 했을때 이슈를 수정하였습니다

2024-11-30 08:10 UTC, seongjxn requested changes

2024-11-30 08:10 UTC, seongjxn commented on lib/src/map.dart
![image](https://github.com/user-attachments/assets/21c65529-b772-4778-b7af-56ddbd5d3acf)

- ln 48 에서 1미터가 맞는지 5미터가 맞는지 한번 확인 부탁드려용

2024-12-03 19:14 UTC, KangJiHyeock commented on lib/src/map.dart
죄송합니다 1미터가 맞습니다

2024-12-08 05:26 UTC, seongjxn approved these changes

2024-12-08 05:42 UTC, merged